services:

  web:
    image: php:8.3-apache
    container_name: php-apache-segunda
    restart: always
    ports:
      - "9000:80"
    volumes:
      - web-data:/var/www/html
volumes:
  web-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./web/src



  #adicionar mysql
  #adicionar meamchache ou redis
